plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'net.neoforged.gradle.userdev' version '7.1.+'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

sourceSets.main.resources {
    srcDir('src/generated/resources')
}

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'

        workingDirectory project.layout.projectDirectory.dir('run').dir(name)

        modSource project.sourceSets.main
    }

    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        argument '--nogui'
    }

    data {
        arguments.addAll(
                '--mod', project.mod_id,
                '--all',
                '--output',
                file('src/generated/resources/').getAbsolutePath(),
                '--existing',
                file('src/main/resources/').getAbsolutePath()
        )
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

repositories {
    // CurseMaven
    maven {
        url "https://cursemaven.com"

        content {
            includeGroup "curse.maven"
        }
    }

    // Curios
    maven {
        url = "https://maven.theillusivec4.top/"
    }

    // GeckoLib
    maven {
        name = 'GeckoLib'
        url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'

        content {
            includeGroupByRegex("software\\.bernie.*")
            includeGroup("com.eliotlash.mclib")
        }
    }

    // Modrinth
    maven {
        name = 'Modrinth'
        url 'https://api.modrinth.com/maven'

        content {
            includeGroup "maven.modrinth"
        }
    }

    mavenCentral()
}

dependencies {
    // =========================
    // NeoForge
    // =========================

    implementation "net.neoforged:neoforge:${neo_version}"


    // =========================
    // Curios
    // =========================

    compileOnly "top.theillusivec4.curios:curios-neoforge:9.2.2+1.21.1:api"

    localRuntime "top.theillusivec4.curios:curios-neoforge:9.2.2+1.21.1"


    // =========================
    // GeckoLib
    // =========================

    implementation "software.bernie.geckolib:geckolib-neoforge-1.21.1:4.7.5"


    // =========================
    // Kotlin for Forge 5.8.0
    //
    // Project ID : 351264
    // File ID    : 8335665
    // MC 1.21.1 対応
    // =========================

    implementation "curse.maven:kotlin-for-forge-351264:8335665"


    // =========================
    // Superb Warfare
    //
    // Modrinth, NeoForge 1.21.1, 0.8.9.1
    // =========================

    implementation "maven.modrinth:superb-warfare:oVcZKrfn"
}

tasks.withType(ProcessResources).configureEach {

    var replaceProperties = [
            minecraft_version       : minecraft_version,
            minecraft_version_range : minecraft_version_range,
            neo_version             : neo_version,
            loader_version_range    : loader_version_range,
            mod_id                  : mod_id,
            mod_name                : mod_name,
            mod_license             : mod_license,
            mod_version             : mod_version,
            mod_authors             : mod_authors,
            mod_description         : mod_description,
    ]

    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.named('jar', Jar).configure {

    manifest {
        attributes([
                "Specification-Title"      : mod_id,
                "Specification-Vendor"     : mod_authors,
                "Specification-Version"    : "1",
                "Implementation-Title"     : project.name,
                "Implementation-Version"   : project.jar.archiveVersion,
                "Implementation-Vendor"    : mod_authors,
                "Implementation-Timestamp" : new Date().format(
                        "yyyy-MM-dd'T'HH:mm:ssZ"
                )
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}