org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.235
loader_version_range=[1,)

mod_id=ashvehicle
mod_name=ashvehicle
mod_license=GPL-3.0
mod_version=1.21.1-4.5.3-8.9-div
mod_group_id=tech.lq0
mod_authors=Arusan
mod_description=It is an addon based on SuperbWarfare
