org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

neo_version=21.1.219
loader_version_range=[1,)

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

curios_version=9.5.1+1.21.1
geckolib_file_id=5763144
superbwarfare_file_id=7292699

mod_id=ashvehicle
mod_name=ashvehicle
mod_license=GPL-3.0
mod_version=1.21.1-4.5.1-8.8
mod_group_id=tech.lq0
mod_authors=Arusan
mod_description=It is an addon based on SuperbWarfare
